controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# config/routes.yaml

app_home:
  path: "/"
  controller: 'App\Controller\HomeController::base'
  methods: ["GET"]

  # config/ParaPharmacie

app_para_pharmacie_index:
  path: "/para/pharmacie/"
  controller: 'App\Controller\ParaPharmacieController::index'
  methods: ["GET"]

app_para_pharmacie_new:
  path: "/para/pharmacie/new"
  controller: 'App\Controller\ParaPharmacieController::new'
  methods: ["GET", "POST"]

app_para_pharmacie_show:
  path: "/para/pharmacie/{id}"
  controller: 'App\Controller\ParaPharmacieController::show'
  methods: ["GET"]
  requirements:
    id: '\d+'

app_para_pharmacie_edit:
  path: "/para/pharmacie/{id}/edit"
  controller: 'App\Controller\ParaPharmacieController::edit'
  methods: ["GET", "POST"]
  requirements:
    id: '\d+'

app_para_pharmacie_delete:
  path: "/para/pharmacie/{id}"
  controller: 'App\Controller\ParaPharmacieController::delete'
  methods: ["POST"]
  requirements:
    id: '\d+'

# config/Zone

app_zone_index:
  path: "/zone/"
  controller: 'App\Controller\ZoneController::index'
  methods: ["GET"]

app_zone_new:
  path: "/zone/new"
  controller: 'App\Controller\ZoneController::new'
  methods: ["GET", "POST"]

app_zone_show:
  path: "/zone/{id}"
  controller: 'App\Controller\ZoneController::show'
  methods: ["GET"]
  requirements:
    id: '\d+'

app_zone_edit:
  path: "/zone/{id}/edit"
  controller: 'App\Controller\ZoneController::edit'
  methods: ["GET", "POST"]
  requirements:
    id: '\d+'

app_zone_delete:
  path: "/zone/{id}"
  controller: 'App\Controller\ZoneController::delete'
  methods: ["POST"]
  requirements:
    id: '\d+'

# config/CategorieEvenement
app_categorie_evenement_index:
  path: /categorie/evenement/
  controller: App\Controller\CategorieEvenementController::index
  methods: GET

app_categorie_evenement_new:
  path: /categorie/evenement/new
  controller: App\Controller\CategorieEvenementController::new
  methods: [GET, POST]

app_categorie_evenement_show:
  path: /categorie/evenement/{id}
  controller: App\Controller\CategorieEvenementController::show
  methods: GET

app_categorie_evenement_edit:
  path: /categorie/evenement/{id}/edit
  controller: App\Controller\CategorieEvenementController::edit
  methods: [GET, POST]

app_categorie_evenement_delete:
  path: /categorie/evenement/{id}
  controller: App\Controller\CategorieEvenementController::delete
  methods: POST
# config/CategorieProduit
app_categorie_prod_index:
  path: /categorie/prod/
  controller: App\Controller\CategorieProdController::index
  methods: GET

app_categorie_prod_new:
  path: /categorie/prod/new
  controller: App\Controller\CategorieProdController::new
  methods: [GET, POST]

app_categorie_prod_show:
  path: /categorie/prod/{id}
  controller: App\Controller\CategorieProdController::show
  methods: GET

app_categorie_prod_edit:
  path: /categorie/prod/{id}/edit
  controller: App\Controller\CategorieProdController::edit
  methods: [GET, POST]

app_categorie_prod_delete:
  path: /categorie/prod/{id}
  controller: App\Controller\CategorieProdController::delete
  methods: POST
# config/Evenement
app_evenement_index:
  path: /evenement/
  controller: App\Controller\EvenementController::index
  methods: GET

app_evenement_new:
  path: /evenement/new
  controller: App\Controller\EvenementController::new
  methods: [GET, POST]

app_evenement_show:
  path: /evenement/{id}
  controller: App\Controller\EvenementController::show
  methods: GET

app_evenement_edit:
  path: /evenement/{id}/edit
  controller: App\Controller\EvenementController::edit
  methods: [GET, POST]

app_evenement_delete:
  path: /evenement/{id}
  controller: App\Controller\EvenementController::delete
  methods: POST
# config/FichePatient
app_fiche_patient_index:
  path: /fiche/patient/
  controller: App\Controller\FichePatientController::index
  methods: GET

app_fiche_patient_new:
  path: /fiche/patient/new
  controller: App\Controller\FichePatientController::new
  methods: [GET, POST]

app_fiche_patient_show:
  path: /fiche/patient/{id}
  controller: App\Controller\FichePatientController::show
  methods: GET

app_fiche_patient_edit:
  path: /fiche/patient/{id}/edit
  controller: App\Controller\FichePatientController::edit
  methods: [GET, POST]

app_fiche_patient_delete:
  path: /fiche/patient/{id}
  controller: App\Controller\FichePatientController::delete
  methods: POST
# config/Medecin
app_medecin_index:
  path: /medecin/
  controller: App\Controller\MedecinController::index
  methods: GET

app_medecin_new:
  path: /medecin/new
  controller: App\Controller\MedecinController::new
  methods: [GET, POST]

app_medecin_show:
  path: /medecin/{id}
  controller: App\Controller\MedecinController::show
  methods: GET

app_medecin_edit:
  path: /medecin/{id}/edit
  controller: App\Controller\MedecinController::edit
  methods: [GET, POST]

app_medecin_delete:
  path: /medecin/{id}
  controller: App\Controller\MedecinController::delete
  methods: POST

# config/Patient
app_patient_index:
  path: /patient/
  controller: App\Controller\PatientController::index
  methods: GET

app_patient_new:
  path: /patient/new
  controller: App\Controller\PatientController::new
  methods: [GET, POST]

app_patient_show:
  path: /patient/{id}
  controller: App\Controller\PatientController::show
  methods: GET

app_patient_edit:
  path: /patient/{id}/edit
  controller: App\Controller\PatientController::edit
  methods: [GET, POST]

app_patient_delete:
  path: /patient/{id}
  controller: App\Controller\PatientController::delete
  methods: POST
# config/Produit
app_produit_index:
  path: /produit/
  controller: App\Controller\ProduitController::index
  methods: GET

app_produit_new:
  path: /produit/new
  controller: App\Controller\ProduitController::new
  methods: [GET, POST]

app_produit_show:
  path: /produit/{id}
  controller: App\Controller\ProduitController::show
  methods: GET

app_produit_edit:
  path: /produit/{id}/edit
  controller: App\Controller\ProduitController::edit
  methods: [GET, POST]

app_produit_delete:
  path: /produit/{id}
  controller: App\Controller\ProduitController::delete
  methods: POST
# config/Specialite
app_specialite_index:
  path: /specialite/
  controller: App\Controller\SpecialiteController::index
  methods: GET

app_specialite_new:
  path: /specialite/new
  controller: App\Controller\SpecialiteController::new
  methods: [GET, POST]

app_specialite_show:
  path: /specialite/{id}
  controller: App\Controller\SpecialiteController::show
  methods: GET

app_specialite_edit:
  path: /specialite/{id}/edit
  controller: App\Controller\SpecialiteController::edit
  methods: [GET, POST]

app_specialite_delete:
  path: /specialite/{id}
  controller: App\Controller\SpecialiteController::delete
  methods: POST
# config/Utilisateur
app_utilisateur_index:
  path: /utilisateur/
  controller: App\Controller\UtilisateurController::index
  methods: GET

app_utilisateur_new:
  path: /utilisateur/new
  controller: App\Controller\UtilisateurController::new
  methods: [GET, POST]

app_utilisateur_show:
  path: /utilisateur/{id}
  controller: App\Controller\UtilisateurController::show
  methods: GET

app_utilisateur_edit:
  path: /utilisateur/{id}/edit
  controller: App\Controller\UtilisateurController::edit
  methods: [GET, POST]

app_utilisateur_delete:
  path: /utilisateur/{id}
  controller: App\Controller\UtilisateurController::delete
  methods: POST
